set(FLATBUFFERS_FLATC_EXECUTABLE ${REZ_FLATBUFFERS_ROOT}/bin/flatc)
set(FLATBUFFERS_INCLUDE_DIR ${REZ_FLATBUFFERS_ROOT}/include)
find_package(FlatBuffers REQUIRED)

set(flatbuffers_INCLUDE_DIRS ${FLATBUFFERS_INCLUDE_DIR})